#!/bin/sh
# -*- sh -*-

case "$1" in
    configure)
        adduser --system --no-create-home smap 2>/dev/null

        mkdir -p /var/run/smap
        chown smap /var/run/smap
        supervisorctl reread
        ;;
esac

#DEBHELPER#
#echo "---- ending postinst $@"
exit 0
