#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'ClimateReport'
# message type.
#

import tinyos.message.Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 37

# The Active Message type associated with this message.
AM_TYPE = -1

class ClimateReport(tinyos.message.Message.Message):
    # Create a new ClimateReport of size 37.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=37):
        tinyos.message.Message.Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <ClimateReport> \n"
        try:
            s += "  [eui64=";
            for i in range(0, 8):
                s += "0x%x " % (self.getElement_eui64(i) & 0xff)
            s += "]\n";
        except:
            pass
        try:
            s += "  [route.hop_limit=0x%x]\n" % (self.get_route_hop_limit())
        except:
            pass
        try:
            s += "  [route.parent=0x%x]\n" % (self.get_route_parent())
        except:
            pass
        try:
            s += "  [route.parent_metric=0x%x]\n" % (self.get_route_parent_metric())
        except:
            pass
        try:
            s += "  [route.parent_etx=0x%x]\n" % (self.get_route_parent_etx())
        except:
            pass
        try:
            s += "  [seq=0x%x]\n" % (self.get_seq())
        except:
            pass
        try:
            s += "  [localTime=0x%x]\n" % (self.get_localTime())
        except:
            pass
        try:
            s += "  [globalTime=0x%x]\n" % (self.get_globalTime())
        except:
            pass
        try:
            s += "  [period=0x%x]\n" % (self.get_period())
        except:
            pass
        try:
            s += "  [readings.temp=";
            for i in range(0, 2):
                s += "0x%x " % (self.getElement_readings_temp(i) & 0xffff)
            s += "]\n";
        except:
            pass
        try:
            s += "  [readings.hum=";
            for i in range(0, 2):
                s += "0x%x " % (self.getElement_readings_hum(i) & 0xffff)
            s += "]\n";
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: eui64
    #   Field type: short[]
    #   Offset (bits): 0
    #   Size of each element (bits): 8
    #

    #
    # Return whether the field 'eui64' is signed (False).
    #
    def isSigned_eui64(self):
        return False
    
    #
    # Return whether the field 'eui64' is an array (True).
    #
    def isArray_eui64(self):
        return True
    
    #
    # Return the offset (in bytes) of the field 'eui64'
    #
    def offset_eui64(self, index1):
        offset = 0
        if index1 < 0 or index1 >= 8:
            raise IndexError
        offset += 0 + index1 * 8
        return (offset / 8)
    
    #
    # Return the offset (in bits) of the field 'eui64'
    #
    def offsetBits_eui64(self, index1):
        offset = 0
        if index1 < 0 or index1 >= 8:
            raise IndexError
        offset += 0 + index1 * 8
        return offset
    
    #
    # Return the entire array 'eui64' as a short[]
    #
    def get_eui64(self):
        tmp = [None]*8
        for index0 in range (0, self.numElements_eui64(0)):
                tmp[index0] = self.getElement_eui64(index0)
        return tmp
    
    #
    # Set the contents of the array 'eui64' from the given short[]
    #
    def set_eui64(self, value):
        for index0 in range(0, len(value)):
            self.setElement_eui64(index0, value[index0])

    #
    # Return an element (as a short) of the array 'eui64'
    #
    def getElement_eui64(self, index1):
        return self.getUIntElement(self.offsetBits_eui64(index1), 8, 1)
    
    #
    # Set an element of the array 'eui64'
    #
    def setElement_eui64(self, index1, value):
        self.setUIntElement(self.offsetBits_eui64(index1), 8, value, 1)
    
    #
    # Return the total size, in bytes, of the array 'eui64'
    #
    def totalSize_eui64(self):
        return (64 / 8)
    
    #
    # Return the total size, in bits, of the array 'eui64'
    #
    def totalSizeBits_eui64(self):
        return 64
    
    #
    # Return the size, in bytes, of each element of the array 'eui64'
    #
    def elementSize_eui64(self):
        return (8 / 8)
    
    #
    # Return the size, in bits, of each element of the array 'eui64'
    #
    def elementSizeBits_eui64(self):
        return 8
    
    #
    # Return the number of dimensions in the array 'eui64'
    #
    def numDimensions_eui64(self):
        return 1
    
    #
    # Return the number of elements in the array 'eui64'
    #
    def numElements_eui64():
        return 8
    
    #
    # Return the number of elements in the array 'eui64'
    # for the given dimension.
    #
    def numElements_eui64(self, dimension):
        array_dims = [ 8,  ]
        if dimension < 0 or dimension >= 1:
            raise IndexException
        if array_dims[dimension] == 0:
            raise IndexError
        return array_dims[dimension]
    
    #
    # Fill in the array 'eui64' with a String
    #
    def setString_eui64(self, s):
         l = len(s)
         for i in range(0, l):
             self.setElement_eui64(i, ord(s[i]));
         self.setElement_eui64(l, 0) #null terminate
    
    #
    # Read the array 'eui64' as a String
    #
    def getString_eui64(self):
        carr = "";
        for i in range(0, 4000):
            if self.getElement_eui64(i) == chr(0):
                break
            carr += self.getElement_eui64(i)
        return carr
    
    #
    # Accessor methods for field: route.hop_limit
    #   Field type: short
    #   Offset (bits): 64
    #   Size (bits): 8
    #

    #
    # Return whether the field 'route.hop_limit' is signed (False).
    #
    def isSigned_route_hop_limit(self):
        return False
    
    #
    # Return whether the field 'route.hop_limit' is an array (False).
    #
    def isArray_route_hop_limit(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'route.hop_limit'
    #
    def offset_route_hop_limit(self):
        return (64 / 8)
    
    #
    # Return the offset (in bits) of the field 'route.hop_limit'
    #
    def offsetBits_route_hop_limit(self):
        return 64
    
    #
    # Return the value (as a short) of the field 'route.hop_limit'
    #
    def get_route_hop_limit(self):
        return self.getUIntElement(self.offsetBits_route_hop_limit(), 8, 1)
    
    #
    # Set the value of the field 'route.hop_limit'
    #
    def set_route_hop_limit(self, value):
        self.setUIntElement(self.offsetBits_route_hop_limit(), 8, value, 1)
    
    #
    # Return the size, in bytes, of the field 'route.hop_limit'
    #
    def size_route_hop_limit(self):
        return (8 / 8)
    
    #
    # Return the size, in bits, of the field 'route.hop_limit'
    #
    def sizeBits_route_hop_limit(self):
        return 8
    
    #
    # Accessor methods for field: route.parent
    #   Field type: int
    #   Offset (bits): 72
    #   Size (bits): 16
    #

    #
    # Return whether the field 'route.parent' is signed (False).
    #
    def isSigned_route_parent(self):
        return False
    
    #
    # Return whether the field 'route.parent' is an array (False).
    #
    def isArray_route_parent(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'route.parent'
    #
    def offset_route_parent(self):
        return (72 / 8)
    
    #
    # Return the offset (in bits) of the field 'route.parent'
    #
    def offsetBits_route_parent(self):
        return 72
    
    #
    # Return the value (as a int) of the field 'route.parent'
    #
    def get_route_parent(self):
        return self.getUIntElement(self.offsetBits_route_parent(), 16, 1)
    
    #
    # Set the value of the field 'route.parent'
    #
    def set_route_parent(self, value):
        self.setUIntElement(self.offsetBits_route_parent(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'route.parent'
    #
    def size_route_parent(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'route.parent'
    #
    def sizeBits_route_parent(self):
        return 16
    
    #
    # Accessor methods for field: route.parent_metric
    #   Field type: int
    #   Offset (bits): 88
    #   Size (bits): 16
    #

    #
    # Return whether the field 'route.parent_metric' is signed (False).
    #
    def isSigned_route_parent_metric(self):
        return False
    
    #
    # Return whether the field 'route.parent_metric' is an array (False).
    #
    def isArray_route_parent_metric(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'route.parent_metric'
    #
    def offset_route_parent_metric(self):
        return (88 / 8)
    
    #
    # Return the offset (in bits) of the field 'route.parent_metric'
    #
    def offsetBits_route_parent_metric(self):
        return 88
    
    #
    # Return the value (as a int) of the field 'route.parent_metric'
    #
    def get_route_parent_metric(self):
        return self.getUIntElement(self.offsetBits_route_parent_metric(), 16, 1)
    
    #
    # Set the value of the field 'route.parent_metric'
    #
    def set_route_parent_metric(self, value):
        self.setUIntElement(self.offsetBits_route_parent_metric(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'route.parent_metric'
    #
    def size_route_parent_metric(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'route.parent_metric'
    #
    def sizeBits_route_parent_metric(self):
        return 16
    
    #
    # Accessor methods for field: route.parent_etx
    #   Field type: int
    #   Offset (bits): 104
    #   Size (bits): 16
    #

    #
    # Return whether the field 'route.parent_etx' is signed (False).
    #
    def isSigned_route_parent_etx(self):
        return False
    
    #
    # Return whether the field 'route.parent_etx' is an array (False).
    #
    def isArray_route_parent_etx(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'route.parent_etx'
    #
    def offset_route_parent_etx(self):
        return (104 / 8)
    
    #
    # Return the offset (in bits) of the field 'route.parent_etx'
    #
    def offsetBits_route_parent_etx(self):
        return 104
    
    #
    # Return the value (as a int) of the field 'route.parent_etx'
    #
    def get_route_parent_etx(self):
        return self.getUIntElement(self.offsetBits_route_parent_etx(), 16, 1)
    
    #
    # Set the value of the field 'route.parent_etx'
    #
    def set_route_parent_etx(self, value):
        self.setUIntElement(self.offsetBits_route_parent_etx(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'route.parent_etx'
    #
    def size_route_parent_etx(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'route.parent_etx'
    #
    def sizeBits_route_parent_etx(self):
        return 16
    
    #
    # Accessor methods for field: seq
    #   Field type: long
    #   Offset (bits): 120
    #   Size (bits): 32
    #

    #
    # Return whether the field 'seq' is signed (False).
    #
    def isSigned_seq(self):
        return False
    
    #
    # Return whether the field 'seq' is an array (False).
    #
    def isArray_seq(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'seq'
    #
    def offset_seq(self):
        return (120 / 8)
    
    #
    # Return the offset (in bits) of the field 'seq'
    #
    def offsetBits_seq(self):
        return 120
    
    #
    # Return the value (as a long) of the field 'seq'
    #
    def get_seq(self):
        return self.getUIntElement(self.offsetBits_seq(), 32, 1)
    
    #
    # Set the value of the field 'seq'
    #
    def set_seq(self, value):
        self.setUIntElement(self.offsetBits_seq(), 32, value, 1)
    
    #
    # Return the size, in bytes, of the field 'seq'
    #
    def size_seq(self):
        return (32 / 8)
    
    #
    # Return the size, in bits, of the field 'seq'
    #
    def sizeBits_seq(self):
        return 32
    
    #
    # Accessor methods for field: localTime
    #   Field type: long
    #   Offset (bits): 152
    #   Size (bits): 32
    #

    #
    # Return whether the field 'localTime' is signed (False).
    #
    def isSigned_localTime(self):
        return False
    
    #
    # Return whether the field 'localTime' is an array (False).
    #
    def isArray_localTime(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'localTime'
    #
    def offset_localTime(self):
        return (152 / 8)
    
    #
    # Return the offset (in bits) of the field 'localTime'
    #
    def offsetBits_localTime(self):
        return 152
    
    #
    # Return the value (as a long) of the field 'localTime'
    #
    def get_localTime(self):
        return self.getUIntElement(self.offsetBits_localTime(), 32, 1)
    
    #
    # Set the value of the field 'localTime'
    #
    def set_localTime(self, value):
        self.setUIntElement(self.offsetBits_localTime(), 32, value, 1)
    
    #
    # Return the size, in bytes, of the field 'localTime'
    #
    def size_localTime(self):
        return (32 / 8)
    
    #
    # Return the size, in bits, of the field 'localTime'
    #
    def sizeBits_localTime(self):
        return 32
    
    #
    # Accessor methods for field: globalTime
    #   Field type: long
    #   Offset (bits): 184
    #   Size (bits): 32
    #

    #
    # Return whether the field 'globalTime' is signed (False).
    #
    def isSigned_globalTime(self):
        return False
    
    #
    # Return whether the field 'globalTime' is an array (False).
    #
    def isArray_globalTime(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'globalTime'
    #
    def offset_globalTime(self):
        return (184 / 8)
    
    #
    # Return the offset (in bits) of the field 'globalTime'
    #
    def offsetBits_globalTime(self):
        return 184
    
    #
    # Return the value (as a long) of the field 'globalTime'
    #
    def get_globalTime(self):
        return self.getUIntElement(self.offsetBits_globalTime(), 32, 1)
    
    #
    # Set the value of the field 'globalTime'
    #
    def set_globalTime(self, value):
        self.setUIntElement(self.offsetBits_globalTime(), 32, value, 1)
    
    #
    # Return the size, in bytes, of the field 'globalTime'
    #
    def size_globalTime(self):
        return (32 / 8)
    
    #
    # Return the size, in bits, of the field 'globalTime'
    #
    def sizeBits_globalTime(self):
        return 32
    
    #
    # Accessor methods for field: period
    #   Field type: int
    #   Offset (bits): 216
    #   Size (bits): 16
    #

    #
    # Return whether the field 'period' is signed (False).
    #
    def isSigned_period(self):
        return False
    
    #
    # Return whether the field 'period' is an array (False).
    #
    def isArray_period(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'period'
    #
    def offset_period(self):
        return (216 / 8)
    
    #
    # Return the offset (in bits) of the field 'period'
    #
    def offsetBits_period(self):
        return 216
    
    #
    # Return the value (as a int) of the field 'period'
    #
    def get_period(self):
        return self.getUIntElement(self.offsetBits_period(), 16, 1)
    
    #
    # Set the value of the field 'period'
    #
    def set_period(self, value):
        self.setUIntElement(self.offsetBits_period(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'period'
    #
    def size_period(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'period'
    #
    def sizeBits_period(self):
        return 16
    
    #
    # Accessor methods for field: readings.temp
    #   Field type: int[]
    #   Offset (bits): 0
    #   Size of each element (bits): 16
    #

    #
    # Return whether the field 'readings.temp' is signed (False).
    #
    def isSigned_readings_temp(self):
        return False
    
    #
    # Return whether the field 'readings.temp' is an array (True).
    #
    def isArray_readings_temp(self):
        return True
    
    #
    # Return the offset (in bytes) of the field 'readings.temp'
    #
    def offset_readings_temp(self, index1):
        offset = 0
        if index1 < 0 or index1 >= 2:
            raise IndexError
        offset += 232 + index1 * 32
        return (offset / 8)
    
    #
    # Return the offset (in bits) of the field 'readings.temp'
    #
    def offsetBits_readings_temp(self, index1):
        offset = 0
        if index1 < 0 or index1 >= 2:
            raise IndexError
        offset += 232 + index1 * 32
        return offset
    
    #
    # Return the entire array 'readings.temp' as a int[]
    #
    def get_readings_temp(self):
        tmp = [None]*2
        for index0 in range (0, self.numElements_readings_temp(0)):
                tmp[index0] = self.getElement_readings_temp(index0)
        return tmp
    
    #
    # Set the contents of the array 'readings.temp' from the given int[]
    #
    def set_readings_temp(self, value):
        for index0 in range(0, len(value)):
            self.setElement_readings_temp(index0, value[index0])

    #
    # Return an element (as a int) of the array 'readings.temp'
    #
    def getElement_readings_temp(self, index1):
        return self.getUIntElement(self.offsetBits_readings_temp(index1), 16, 1)
    
    #
    # Set an element of the array 'readings.temp'
    #
    def setElement_readings_temp(self, index1, value):
        self.setUIntElement(self.offsetBits_readings_temp(index1), 16, value, 1)
    
    #
    # Return the total size, in bytes, of the array 'readings.temp'
    #
    def totalSize_readings_temp(self):
        return (64 / 8)
    
    #
    # Return the total size, in bits, of the array 'readings.temp'
    #
    def totalSizeBits_readings_temp(self):
        return 64
    
    #
    # Return the size, in bytes, of each element of the array 'readings.temp'
    #
    def elementSize_readings_temp(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of each element of the array 'readings.temp'
    #
    def elementSizeBits_readings_temp(self):
        return 16
    
    #
    # Return the number of dimensions in the array 'readings.temp'
    #
    def numDimensions_readings_temp(self):
        return 1
    
    #
    # Return the number of elements in the array 'readings.temp'
    #
    def numElements_readings_temp():
        return 2
    
    #
    # Return the number of elements in the array 'readings.temp'
    # for the given dimension.
    #
    def numElements_readings_temp(self, dimension):
        array_dims = [ 2,  ]
        if dimension < 0 or dimension >= 1:
            raise IndexException
        if array_dims[dimension] == 0:
            raise IndexError
        return array_dims[dimension]
    
    #
    # Accessor methods for field: readings.hum
    #   Field type: int[]
    #   Offset (bits): 16
    #   Size of each element (bits): 16
    #

    #
    # Return whether the field 'readings.hum' is signed (False).
    #
    def isSigned_readings_hum(self):
        return False
    
    #
    # Return whether the field 'readings.hum' is an array (True).
    #
    def isArray_readings_hum(self):
        return True
    
    #
    # Return the offset (in bytes) of the field 'readings.hum'
    #
    def offset_readings_hum(self, index1):
        offset = 16
        if index1 < 0 or index1 >= 2:
            raise IndexError
        offset += 232 + index1 * 32
        return (offset / 8)
    
    #
    # Return the offset (in bits) of the field 'readings.hum'
    #
    def offsetBits_readings_hum(self, index1):
        offset = 16
        if index1 < 0 or index1 >= 2:
            raise IndexError
        offset += 232 + index1 * 32
        return offset
    
    #
    # Return the entire array 'readings.hum' as a int[]
    #
    def get_readings_hum(self):
        tmp = [None]*2
        for index0 in range (0, self.numElements_readings_hum(0)):
                tmp[index0] = self.getElement_readings_hum(index0)
        return tmp
    
    #
    # Set the contents of the array 'readings.hum' from the given int[]
    #
    def set_readings_hum(self, value):
        for index0 in range(0, len(value)):
            self.setElement_readings_hum(index0, value[index0])

    #
    # Return an element (as a int) of the array 'readings.hum'
    #
    def getElement_readings_hum(self, index1):
        return self.getUIntElement(self.offsetBits_readings_hum(index1), 16, 1)
    
    #
    # Set an element of the array 'readings.hum'
    #
    def setElement_readings_hum(self, index1, value):
        self.setUIntElement(self.offsetBits_readings_hum(index1), 16, value, 1)
    
    #
    # Return the total size, in bytes, of the array 'readings.hum'
    #
    def totalSize_readings_hum(self):
        return (64 / 8)
    
    #
    # Return the total size, in bits, of the array 'readings.hum'
    #
    def totalSizeBits_readings_hum(self):
        return 64
    
    #
    # Return the size, in bytes, of each element of the array 'readings.hum'
    #
    def elementSize_readings_hum(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of each element of the array 'readings.hum'
    #
    def elementSizeBits_readings_hum(self):
        return 16
    
    #
    # Return the number of dimensions in the array 'readings.hum'
    #
    def numDimensions_readings_hum(self):
        return 1
    
    #
    # Return the number of elements in the array 'readings.hum'
    #
    def numElements_readings_hum():
        return 2
    
    #
    # Return the number of elements in the array 'readings.hum'
    # for the given dimension.
    #
    def numElements_readings_hum(self, dimension):
        array_dims = [ 2,  ]
        if dimension < 0 or dimension >= 1:
            raise IndexException
        if array_dims[dimension] == 0:
            raise IndexError
        return array_dims[dimension]
    
